# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  [AUTOMATIC ANSWER] Thanks for opening your first pull request here! 💖 Please check out our [contributing guidelines]().

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  [AUTOMATIC ANSWER] Congrats on merging your first pull request! 🎉🎉🎉

# It is recommend to include as many gifs and emojis as possible
